# src/Tomaz/BlogElastikaBundle/Resources/config/routing.yml
TomazBlogElastikaBundle_homepage:
    pattern:  /
    defaults: { _controller: TomazBlogElastikaBundle:Page:index }
    requirements:
        _method:  GET

TomazBlogElastikaBundle_about:
    pattern: /about
    defaults: { _controller: TomazBlogElastikaBundle:Page:about }
    requirements:
        _method:  GET

TomazBlogElastikaBundle_contact:
    pattern: /contact
    defaults: { _controller: TomazBlogElastikaBundle:Page:contact }
    requirements:
        _method:  GET|POST

TomazBlogElastikaBundle_blog_show:
    pattern: /{id}
    defaults: { _controller: TomazBlogElastikaBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+